### ISSUE TITLE
Downloading an episode causes a calendar event

### ISSUE THREAD

**Issue by eli-b** [yuvaldrori/Forty#2]
I (re-)downloaded many episodes in the same day, causing my calendar for Tuesday to look like:
![image](https://user-images.githubusercontent.com/834999/30168767-0785c038-93f3-11e7-8443-e0ffb2a02762.png)

While funny, I guess no calendar event should be generated just for downloading an episode on PocketCasts.

**Comment by yuvaldrori** [comment]
I don't get a calendar event when downloading the episodes for the first time, how do you remember download an episode.

**Comment by eli-b** [comment]
Sorry. I forgot I had to briefly try to play each episode in order to get an error message, delete and re-download each episode. The calendar events were probably created because of the brief attempt to play each episode.
All of the episodes on my phone we corrupted when I changed my default download location to the external memory card.

**Comment by yuvaldrori** [comment]
I love it when you close your own bugs...
